language: python
sudo: false
python:
  - 3.6

script: env

jobs:
  include:
    script: env
    deploy:
      - provider: script
        script: echo 'first deployment'
      - provider: script
        script: echo 'second deployment'
