language: python
sudo: false
python:
  - 3.6

script: env


jobs:
  include:
    script: 
      - env
      - shell_session_update() { :; };
    deploy:
      - provider: script
        skip_cleanup: true
        script: echo 'first deployment'
        on:
          tags: true
          branch: master
          repo: ulope/travistest
      - provider: script
        skip_cleanup: true
        script: ./deploy_script.sh 'second deployment' $HOME
        on:
          repo: ulope/travistest
