language: python
sudo: false
python:
  - 3.6

script: env


jobs:
  include:
    script: env
    deploy:
      - provider: script
        skip_cleanup: true
        script: echo 'first deployment'
        on:
          tags: true
          branch: master
      - provider: script
        skip_cleanup: true
        script: echo 'second deployment'
        on:
          branch: master

